version: 2.1

jobs:
  test: # Also lints first
    docker:
      - image: circleci/php:8.0
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN

    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}

      - run: composer install --no-interaction

      - save_cache:
          paths:
            - vendor
          key: composer-v1-{{ checksum "composer.lock" }}

      - run: composer run lint:check
      - run: composer run test

workflows:
  build:
    jobs:
      - test:
          context:
            - docker-hub-creds
